[project]
name = "symcelerator"
version = "1.0.0"
dependencies = [
    'cppyy',
    'matplotlib'
]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = { find = { where = ["src"]}}