[project]
name = "symcelerator"
version = "1.0.0"
dependencies = [
    'cppyy',
    'matplotlib'
]
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"